import { PrismaClient } from "@prisma/client";
const db = new PrismaClient();

async function main() {
  
  await db.template.createMany({
    data: [
      {
        id: "66df3b21f4a1c8b6978ef58d",
        title: "Sports ecommerce website landing page",
        description:
          "Gear up for success with the best in sports apparel, footwear, and accessories. Discover top brands, performance-driven products, and exclusive deals to elevate your game. Shop now and stay ahead in style!",
        longDescription:
          "Welcome to the ultimate destination for sports enthusiasts! Whether you’re a professional athlete or just starting your fitness journey, we have everything you need to achieve your goals. Explore a wide range of premium sports apparel, high-performance footwear, and cutting-edge gear from the world’s leading brands. From running shoes to training equipment, outdoor essentials to yoga wear, we’ve got you covered. Enjoy exclusive offers, fast shipping, and seamless shopping. Step up your game with the right gear and push your limits like never before! Plus, take advantage of personalized recommendations, expert advice, and fitness tips tailored to your needs. With a focus on innovation and quality, we help you stay at the top of your game—every step of the way.",
        theme: "light",
        category: ["sports", "e_commerce", "light_theme", "2d", "landing_page"],
        access: "Pro",
        price: 19,
        platform: ["azeorex"],
        feature: ["Modern ecommerce design", "Professional sports template", "Creative landing page", "UI UX services"],
        image: [
          "https://res.cloudinary.com/dv86lqkcy/image/upload/v1725898367/image_qdwxmd.png",
          "https://res.cloudinary.com/dv86lqkcy/image/upload/v1730610728/Mockup_htwl2t.png",
          "https://res.cloudinary.com/dv86lqkcy/image/upload/v1730136103/MacBook_Pro_14__-_18_1_vhdpya.png",
        ],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 98,
        dislikes: 8,
        likesArray: [],
      },
      {
        id: "66e273ef1857c699f5cdfd86",
        title: "Fashion ecommerce website ",
        description: "Hello everyone!  Here is a Fashion E-commerce web design concept.  Feel free to leave valuable feedback and don't forget to press ❤",
        longDescription:
          "The home page of this fashion eCommerce template is sleek and modern, designed to captivate visitors. It features a clean layout with high-quality images, bold typography, and intuitive navigation. A featured products section highlights the latest trends, while seamless product categorization ensures a smooth shopping experience for fashion enthusiasts.",
        theme: "light",
        category: ["business", "e_commerce", "light_theme", "2d", "landing_page"],
        access: "Free",
        price: 0,
        platform: ["figma"],
        feature: ["UI Design", "Modarn ecommerce design", "Fashion ecommerce home page", "Landing page", "Attractive design"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726111617/Mockup16_vzsu3s.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 101,
        dislikes: 8,
        likesArray: ["12e39b3e-1298-4bc4-8935-13a08a536ac5"],
      },
      {
        id: "66e2bfdffafc0bafd67c639d",
        title: "Ed-tech website home page",
        description:
          "The EdTech homepage offers a clean layout with a featured courses section, easy navigation, and student testimonials. Vibrant visuals and clear call-to-actions guide users to explore content, sign up for courses, and stay updated with the latest learning resources.",
        longDescription:
          "The homepage of the EdTech website template is designed to engage learners and educators with a clean, intuitive layout. It features a hero section showcasing key courses, an easy-to-navigate course catalogs, and testimonials from successful students. With vibrant visuals and clear call-to-action buttons, visitors can effortlessly explore educational content, sign up for courses, and stay updated with the latest learning trends and resources",
        theme: "light",
        category: ["business", "ed-tech", "2d", "landing_page", "light_theme"],
        access: "Pro",
        price: 19,
        platform: ["azeorex"],
        feature: ["Website landing Design", "User-Friendly Interface", "Higher Retention", "Particular Course Catalog", "Leatest UI Design", "Provided Course Ratings"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726135152/Mockup21_d2w1op.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 101,
        dislikes: 8,
        likesArray: ["12e39b3e-1298-4bc4-8935-13a08a536ac5"],
      },
      {
        id: "66e2d1178cf9ed12e37d6ac9",
        title: "Designer portfolio  website landing page",
        description: "The homepage of the designer portfolio template features a clean, modern design with a hero section, an interactive project showcase section, and engage clients.",
        longDescription:
          "The homepage of the designer portfolio website template showcases a clean, modern layout to highlight your creative work. A hero section introduces your personal brand with a stunning image . Below, featured projects are displayed in an interactive grid, each linking to detailed case studies. The minimalistic design , ensuring your portfolio stands out and engages potential clients effortlessly.",
        theme: "light",
        category: ["light_theme", "2d", "landing_page", "personal", "business"],
        access: "Pro",
        price: 12,
        platform: ["figma"],
        feature: ["Attractive UI", "Clean Layout", "Social Media Integration", "Showcase Creativity", "Professional Appearance", "User-Friendly"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726139507/Mockup22_fk8vpo.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 101,
        dislikes: 8,
        likesArray: ["12e39b3e-1298-4bc4-8935-13a08a536ac5"],
      },
      {
        id: "66e2e9ce6987386fdb46bb0d",
        title: "Blog home page",
        description:
          "Welcome to our blog! Explore trending topics, featured articles, and insightful posts on business, tech, and lifestyle. Stay updated and inspired with fresh content, all in a sleek, easy-to-navigate design.",
        longDescription:
          "Welcome to our blog, where ideas come to life! Our home page provides a clean, modern design with easy navigation, making it simple to explore various articles and categories. Stay updated with the latest insights on business, tech, and lifestyle. Discover trending topics, featured posts, and in-depth articles to inspire your next big project. Join our community of curious minds and start exploring today!",
        theme: "light",
        category: ["business", "2d", "light_theme", "blog", "landing_page", "personal"],
        access: "Pro",
        price: 19,
        platform: ["figma"],
        feature: ["Minimalistic UI Design", "Modern Design", "User-friendly", "User login option", "Easy navigation", "Search bar"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726146388/Mockup23_rztv58.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 100,
        dislikes: 8,
        likesArray: [],
      },
      {
        id: "66e44e4099e254816eee6b40",
        title: "Sports Website UI",
        description: "A sleek, modern sports website UI featuring live scores, news, team stats, player profiles, and interactive match highlights.",
        longDescription:
          "A sports website UI should feature a dynamic, responsive design with live scores, team stats, and news updates. It should include a visually appealing layout, easy navigation, and interactive elements like player profiles, match schedules, and fan engagement features to enhance the user experience across devices.",
        theme: "light",
        category: ["business", "sports", "landing_page", "light_theme", "2d"],
        access: "Pro",
        price: 19,
        platform: ["azeorex"],
        feature: ["Modern UI", "Attractive design", "Match Schedules", "News and Updates Section"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726236911/Mockup_r9ziig.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 119,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e4567126feb47978e82a92",
        title: "Ecommerce Website: Fashion",
        description: "Discover the latest fashion trends with a sleek, modern homepage featuring curated collections, new arrivals, and exclusive offers. Shop effortlessly.",
        longDescription:
          "Our fashion e-commerce homepage offers a sleek and stylish design to showcase your latest collections. With a clean, intuitive layout, visitors can effortlessly browse categories, discover trending items, and explore featured products. The homepage highlights special offers, new arrivals, and popular picks, while a user-friendly navigation ensures seamless shopping. A prominent search bar and personalized recommendations make it easy for customers to find exactly what they’re looking for.",
        theme: "light",
        category: ["business", "light_theme", "e_commerce", "2d", "landing_page"],
        access: "Pro",
        price: 19,
        platform: ["figma"],
        feature: ["Easy navigation", "Clean, modern design", "Attractive layout", "User login option", "User-friendly"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726238999/Shopping_website_ardr3t.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e575274da40a43a6b0bd9d",
        title: "Designer Website",
        description: "A sleek, modern designer website template featuring portfolio showcases, responsive design, and customizable layouts for creative professionals.",
        longDescription:
          "This designer website template is crafted for creative professionals looking to showcase their portfolio with style and elegance. Featuring a sleek, modern design, it offers fully customizable layouts that highlight your work in the best light. It's perfect for designers, artists  and anyone seeking a professional yet creative online presence. This template is the ultimate tool to elevate your portfolio.",
        theme: "light",
        category: ["2d", "light_theme", "personal", "landing_page", "business"],
        access: "Pro",
        price: 11,
        platform: ["figma"],
        feature: ["User-friendly navigation", "Desktop version", "High-quality visuals", "light theme", "Personal website layout", "Bold typography"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726311214/Mockup24_xv2hv4.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726311389/Mockup25_bbciew.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e57aa84da40a43a6b0bdab",
        title: "Website design for Educational platform",
        description:
          "A modern educational platform template featuring a clean,intuitive navigation, course catalog, interactive learning modules, and seamless integration for video lessons, and progress tracking.",
        longDescription:
          "This educational platform template is designed to offer a comprehensive, user-friendly learning experience. Featuring a modern, it provides easy navigation for students and educators alike. The template includes a robust course catalog,  and interactive learning modules that promote engagement. Seamless integration of video lessons, and assignments ensures a dynamic learning environment. Progress tracking features allow students to monitor their achievements, while educators can manage courses and assess performance with ease. Ideal for e-learning, tutoring, or online training platforms, this template supports scalability and customization to meet the evolving needs of educational institutions.",
        theme: "light",
        category: ["business", "ed-tech", "light_theme", "2d", "landing_page"],
        access: "Pro",
        price: 19,
        platform: ["azeorex"],
        feature: ["One page application", "Bold typography", "User friendly", "light theme", "Robust course catalog", "Video  lessons", "Modern UI", "Provided Course Ratings"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726314208/Mockup26_qomfvx.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726314235/Mockup27_nope67.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e5901f4b95ab32da621691",
        title: "SaaS Website",
        description: "Modern SaaS landing page template with sleek design, responsive layout, and customizable components. Optimize conversions and showcase features effortlessly.",
        longDescription:
          "Elevate your SaaS business with our sleek and modern landing page template, designed to captivate and convert. Featuring a clean layout, intuitive navigation, and customizable components, this template provides everything you need to showcase your product's features, benefits, and pricing. Built with performance and user experience in mind, it's fully responsive and optimized for fast load times. Whether you're launching a new product or boosting your current online presence, this template offers seamless integration with popular tools and services, making it the perfect solution for your SaaS needs.",
        theme: "dark",
        category: ["business", "2d", "dark_theme", "landing_page", "saas"],
        access: "Pro",
        price: 29,
        platform: ["azeorex"],
        feature: ["Dark theme", "modern UI", "Featuring a clean layout", "intuitive navigation"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726319506/Mockup28_lsrxi1.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726319541/Mockup29_av4tiu.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e593dc4b95ab32da62169a",
        title: "Sports website",
        description:
          "A sleek, modern sports website template featuring live scores, team stats, player profiles, match schedules, and news updates. Ideal for sports blogs, clubs, and leagues to engage fans and showcase content.",
        longDescription:
          "This dynamic sports website template is designed for sports clubs, leagues, and enthusiasts. It includes sections for live scores, player and team statistics, match schedules, and in-depth news coverage. The homepage showcases featured events, top athletes, and upcoming matches, while the blog section keeps visitors updated with the latest sports news. With customizable layouts, it's perfect for creating an engaging online presence that highlights your sports passion and connects with fans.",
        theme: "light",
        category: ["business", "sports", "2d", "landing_page", "light_theme"],
        access: "Pro",
        price: 19,
        platform: ["azeorex"],
        feature: ["Modern UI", "Attractive design", "Match schedules", "News section", "Sports category section", "One page layout"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726320957/Mockup10_jh8cse.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726320900/Mockup9_uvm4bl.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e597f14b95ab32da6216b3",
        title: "Fashion ecommerce website",
        description:
          "Discover the latest trends in fashion with our sleek, user-friendly homepage. Explore curated collections, featured products, and exclusive offers, all designed for a seamless shopping experience.",
        longDescription:
          "Welcome to our fashion-forward online store, where style meets convenience! Explore the latest trends in clothing, accessories, and footwear, all curated to elevate your wardrobe. Our homepage features a sleek, user-friendly design with intuitive navigation, making it easy to browse by category, shop by collection, or discover new arrivals. Enjoy personalized recommendations, exclusive offers . Stay connected with our newsletter for the latest updates and special promotions, all while enjoying a visually stunning..",
        theme: "light",
        category: ["business", "e_commerce", "2d", "light_theme", "landing_page"],
        access: "Pro",
        price: 11,
        platform: ["figma"],
        feature: ["Fashion ecommerce home page", "mordern UI", "Attractive design", "One page design", "Light theme"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726322080/Mockup11_cvbqrq.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726322212/Mockup12_mjswmc.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e7c8ced51fa9cd140f44f9",
        title: "Fashion ecommerce website",
        description:
          "A stylish and modern e-commerce homepage designed for fashion brands. Featuring sleek navigation, high-quality product images, and a clean layout, it offers seamless browsing. Highlighted collections, new arrivals, and exclusive offers engage visitors immediately. Perfect for showcasing your brand’s style.",
        longDescription:
          'The homepage of this fashion e-commerce website template is sleek, modern, and visually captivating. It features a full-width hero banner showcasing the latest collections, followed by trending categories like dresses, footwear, and accessories. A "New Arrivals" section highlights the hottest products, while the "Best Sellers" segment showcases popular items. The clean, user-friendly layout ensures easy navigation, with quick links to sales, promotions, and customer reviews. The homepage is designed to engage users immediately, offering an immersive shopping experience from the first click.',
        theme: "light",
        category: ["business", "e_commerce", "light_theme", "2d", "landing_page"],
        access: "Pro",
        price: 15,
        platform: ["figma"],
        feature: ["One page layout", "Light theme", "Modern UI", "Attractive design"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726464611/Mockup19_wmgmkf.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726464694/Mockup20_cdbxm9.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e7cf4cb73c77e8b443556f",
        title: "Designer Portfolio",
        description:
          '"Welcome to my design portfolio, where creativity meets functionality. Explore a curated collection of projects showcasing innovative design solutions across web, mobile, and branding. Let\'s bring your vision to life."',
        longDescription:
          "The homepage of the designer portfolio website serves as a stunning introduction to your creative expertise. With a clean, minimal layout, it highlights your best work through high-quality visuals and engaging interactions. Visitors are welcomed by a captivating hero section, showcasing your latest projects, followed by an easy-to-navigate menu that guides them to various portfolio categories, testimonials, and contact information. The page is designed to make a lasting impression, reflecting your unique style and professionalism while offering a seamless user experience.",
        theme: "light",
        category: ["business", "2d", "light_theme", "landing_page", "personal"],
        access: "Pro",
        price: 12,
        platform: ["figma"],
        feature: ["Modern UI", "Attractive design", "One page layout", "Personalized branding", "Social media integration"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726467433/Mockup32_mi9fow.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726467447/Mockup33_hysdah.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e7d28db73c77e8b4435577",
        title: "Blog website design",
        description:
          "The blog website design offers a clean, user-friendly layout with featured posts, easy navigation, ensuring an engaging reading experience across all devices while highlighting key content.",
        longDescription:
          "The blog website design features a clean, modern layout tailored for an engaging user experience.It adapts seamlessly to all devices, ensuring readers can easily access content on the go. The homepage highlights featured posts and trending topics, while an intuitive navigation menu allows users to explore various categories effortlessly. Integrated social sharing buttons, a search bar, and a comment section encourage interaction, making it a dynamic platform for both readers and content creators to connect and engage.",
        theme: "light",
        category: ["business", "blog", "2d", "light_theme", "landing_page", "personal"],
        access: "Pro",
        price: 20,
        platform: ["figma"],
        feature: ["Blog", "One page", "Light theme", "Attractive UI", "Featured posts", "Search bar", "Minimalistic readable design", "Enhanced user experience"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726468035/Mockup30_ay0irj.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726468087/Mockup31_ncbrfx.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e7d979abf60dbe923c3b77",
        title: "SaaS website",
        description:
          "A SaaS website offering a sleek, user-friendly interface with powerful features like real-time analytics, seamless integrations, and automated workflows to streamline operations, enhance productivity, and deliver a top-tier digital experience.",
        longDescription:
          "The SaaS website features a sleek, user-friendly interface designed for efficiency and ease of use. It offers a customizable dashboard, real-time analytics, and robust integration options to streamline operations. With responsive design and high-performance capabilities, users can access their data and tools seamlessly across all devices. Security is a top priority, with built-in encryption and authentication. The platform also supports multi-language options, automated workflows, and interactive features to enhance user engagement and operational efficiency.",
        theme: "dark",
        category: ["business", "dark_theme", "2d", "saas", "landing_page"],
        access: "Pro",
        price: 25,
        platform: ["figma"],
        feature: ["Saas website", "One page", "Dark mode design", "Enhanced user focus", "Increased customer satisfaction", "Modern aesthetic"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726469657/Mockup34_pcgf4p.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726469601/Mockup35_xriihx.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e7e457438121359030de3c",
        title: "Sport website design",
        description: "A sleek, modern sports website UI featuring live scores, news, team stats, player profiles, and interactive match highlights.",
        longDescription:
          "A sports website UI should feature a dynamic, responsive design with live scores, team stats, and news updates. It should include a visually appealing layout, easy navigation, and interactive elements like player profiles, match schedules, and fan engagement features to enhance the user experience across devices.",
        theme: "light",
        category: ["business", "sports", "light_theme", "2d", "landing_page", "blog"],
        access: "Pro",
        price: 19,
        platform: ["figma"],
        feature: ["User Login and Profile Customization", "One Page", "Social Media Integration", "Sport Category", "News and Updates Section", "Match Schedules", "Live Scores Widget"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726470654/Mockup7_l2oib3.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726470686/Mockup8_gljqvq.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e869e35109753f76baa6c4",
        title: "Ed-tech Website UI",
        description:
          "The EdTech homepage offers a clean layout with a featured courses section, easy navigation, and student testimonials. Vibrant visuals and clear call-to-actions guide users to explore content, sign up for courses, and stay updated with the latest learning resources.",
        longDescription:
          "This educational platform template is designed to offer a comprehensive, user-friendly learning experience. Featuring a modern, it provides easy navigation for students and educators alike. The template includes a robust course catalog, and interactive learning modules that promote engagement. Seamless integration of video lessons, and assignments ensures a dynamic learning environment. Progress tracking features allow students to monitor their achievements, while educators can manage courses and assess performance with ease. Ideal for e-learning, tutoring, or online training platforms, this template supports scalability and customization to meet the evolving needs of educational institutions.",
        theme: "light",
        category: ["business", "ed-tech", "light_theme", "2d", "landing_page"],
        access: "Pro",
        price: 19,
        platform: ["figma"],
        feature: ["Mordern UI", "Light Theme", "Bold typography", "Video lessons", "Provided Course Ratings", "One Page Layout"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726507208/Mockup36_gydpa1.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726507227/Mockup37_dafelm.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e9c0768e5ec92f80361769",
        title: "Fashion ecommerce website",
        description:
          "A stylish and modern e-commerce homepage designed for fashion brands. Featuring sleek navigation, high-quality product images, and a clean layout, it offers seamless browsing. Highlighted collections, new arrivals, and exclusive offers engage visitors immediately. Perfect for showcasing your brand’s style.",
        longDescription:
          'The homepage of this fashion e-commerce website template is sleek, modern, and visually captivating. It features a full-width hero banner showcasing the latest collections, followed by trending categories like dresses, footwear, and accessories. A "New Arrivals" section highlights the hottest products, while the "Best Sellers" segment showcases popular items. The clean, user-friendly layout ensures easy navigation, with quick links to sales, promotions, and customer reviews. The homepage is designed to engage users immediately, offering an immersive shopping experience from the first click.',
        theme: "light",
        category: ["business", "e_commerce", "light_theme", "2d", "landing_page"],
        access: "Pro",
        price: 9,
        platform: ["figma"],
        feature: ["Light theme layout", "One page layout", "Login features", "Modern UI", "Attractive design"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726594062/Mockup17_aqbda3.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726594931/Mockup18_vu8afi.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e9c4d41a86a62433e823c5",
        title: "Ed-tech Website Design",
        description:
          "The EdTech homepage offers a clean layout with a featured courses section, easy navigation, and student testimonials. Vibrant visuals and clear call-to-actions guide users to explore content, sign up for courses, and stay updated with the latest learning resources.",
        longDescription:
          "This educational platform template is designed to offer a comprehensive, user-friendly learning experience. Featuring a modern, it provides easy navigation for students and educators alike. The template includes a robust course catalog, and interactive learning modules that promote engagement. Seamless integration of video lessons, and assignments ensures a dynamic learning environment. Progress tracking features allow students to monitor their achievements, while educators can manage courses and assess performance with ease. Ideal for e-learning, tutoring, or online training platforms, this template supports scalability and customization to meet the evolving needs of educational institutions.",
        theme: "light",
        category: ["business", "ed-tech", "2d", "landing_page", "light_theme"],
        access: "Pro",
        price: 19,
        platform: ["figma"],
        feature: [
          "One page layout",
          "Modern UI",
          "User-friendly  interface",
          "Video lectures and tutorials",
          "Light theme",
          "Bold typography",
          "Provided Course Ratings",
          "Higher Retention",
          "Particular Course Catalog",
        ],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726595613/Mockup41_k2unkh.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726595579/Mockup40_hdumkb.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e9c7737a18d96857cd1d38",
        title: "SaaS website",
        description:
          "A SaaS website offering a sleek, user-friendly interface with powerful features like real-time analytics, seamless integrations, and automated workflows to streamline operations, enhance productivity, and deliver a top-tier digital experience.",
        longDescription:
          "The SaaS website features a sleek, user-friendly interface designed for efficiency and ease of use. It offers a customizable dashboard, real-time analytics, and robust integration options to streamline operations. With responsive design and high-performance capabilities, users can access their data and tools seamlessly across all devices. Security is a top priority, with built-in encryption and authentication. The platform also supports multi-language options, automated workflows, and interactive features to enhance user engagement and operational efficiency.",
        theme: "dark",
        category: ["business", "saas", "2d", "dark_theme", "landing_page"],
        access: "Pro",
        price: 29,
        platform: ["figma"],
        feature: ["Saas website", "One page layout", "Dark mode design", "Enhanced user focus", "Increased customer satisfaction", "Modern UI"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726596710/Mockup42_jqtwee.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726596750/Mockup43_whlneq.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e9ca0e1a86a62433e823cb",
        title: "Designer Portfolio Website",
        description: "A sleek, modern designer portfolio website template featuring portfolio showcases, responsive design, and customizable layouts for creative professionals.",
        longDescription:
          "This designer website template is crafted for creative professionals looking to showcase their portfolio with style and elegance. Featuring a sleek, modern design, it offers fully customizable layouts that highlight your work in the best light. It's perfect for designers, artists and anyone seeking a professional yet creative online presence. This template is the ultimate tool to elevate your portfolio.",
        theme: "light",
        category: ["business", "2d", "light_theme", "personal", "landing_page"],
        access: "Pro",
        price: 12,
        platform: ["figma"],
        feature: ["User-friendly navigation", "Desktop version", "High-quality visuals", "light theme", "One page latout", "Personal website layout", "Bold typography"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726597430/Mockup44_r6exib.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726597436/Mockup45_mpe74s.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e9cb3d1a86a62433e823d2",
        title: "Sport Website Layout",
        description:
          "A sleek, modern sports website template featuring live scores, team stats, player profiles, match schedules, and news updates. Ideal for sports blogs, clubs, and leagues to engage fans and showcase content.",
        longDescription:
          "This dynamic sports website template is designed for sports clubs, leagues, and enthusiasts. It includes sections for live scores, player and team statistics, match schedules, and in-depth news coverage. The homepage showcases featured events, top athletes, and upcoming matches, while the blog section keeps visitors updated with the latest sports news. With customizable layouts, it's perfect for creating an engaging online presence that highlights your sports passion and connects with fans.",
        theme: "light",
        category: ["business", "sports", "light_theme", "2d", "landing_page"],
        access: "Free",
        price: 0,
        platform: ["figma"],
        feature: ["One page layout", "Attractive design", "Sports category section", "Match schedules", "Letest UI"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726597701/Mockup5_e7u3o8.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726597721/Mockup6_p92yku.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66e9cd591a86a62433e823eb",
        title: "Ed-tech Website Design",
        description:
          "The EdTech homepage offers a clean layout with a featured courses section, easy navigation, and student testimonials. Vibrant visuals and clear call-to-actions guide users to explore content, sign up for courses, and stay updated with the latest learning resources.",
        longDescription:
          "This educational platform template is designed to offer a comprehensive, user-friendly learning experience. Featuring a modern, it provides easy navigation for students and educators alike. The template includes a robust course catalog, and interactive learning modules that promote engagement. Seamless integration of video lessons, and assignments ensures a dynamic learning environment. Progress tracking features allow students to monitor their achievements, while educators can manage courses and assess performance with ease. Ideal for e-learning, tutoring, or online training platforms, this template supports scalability and customization to meet the evolving needs of educational institutions.",
        theme: "light",
        category: ["business", "ed-tech", "2d", "light_theme", "landing_page"],
        access: "Pro",
        price: 19,
        platform: ["figma"],
        feature: [
          "One page layout",
          "Letest UI",
          "User-friendly interface",
          "Video lectures and tutorials",
          "Light theme",
          "Bold typography",
          "Provided Course Ratings",
          "Higher Retention",
          "Particular Course Catalog",
        ],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726598284/Mockup39_toyjk9.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726598277/Mockup38_xlrcxm.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66eac25a568a4f229637f9b3",
        title: "Designer Portfolio Landing Page",
        description: "This is a Portfolio Website exploration. Hope you guys will like it. Let me know your thoughts on that. Your feedback and appreciation is always welcome 🙂",
        longDescription:
          "This designer website template is crafted for creative professionals looking to showcase their portfolio with style and elegance. Featuring a sleek, modern design, it offers fully customizable layouts that highlight your work in the best light. It's perfect for designers, artists and anyone seeking a professional yet creative online presence. This template is the ultimate tool to elevate your portfolio.",
        theme: "light",
        category: ["business", "light_theme", "2d", "landing_page", "personal"],
        access: "Pro",
        price: 9,
        platform: ["figma"],
        feature: [
          "Desktop version",
          "High-quality visuals",
          "light theme",
          "One page latout",
          "Personal website layout",
          "Bold typography",
          "Skill section",
          "Work section",
          "Social media intrigration",
          "Letest UI",
        ],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726660738/Mockup47_ib1nuh.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726660746/Mockup46_ciorcm.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66eac595568a4f229637f9cc",
        title: "Blog home page — Blog Sopt UI",
        description:
          "The blog home page design offers a clean, user-friendly layout with featured posts, easy navigation, ensuring an engaging reading experience across all devices while highlighting key content.",
        longDescription:
          "The blog home page design features a clean, modern layout tailored for an engaging user experience. It adapts seamlessly to all devices, ensuring readers can easily access content on the go. The homepage highlights featured posts and trending topics, while an intuitive navigation menu allows users to explore various categories effortlessly. Integrated social sharing buttons, a search bar, and a comment section encourage interaction, making it a dynamic platform for both readers and content creators to connect and engage.",
        theme: "light",
        category: ["business", "light_theme", "2d", "landing_page", "blog"],
        access: "Pro",
        price: 15,
        platform: ["figma"],
        feature: ["Blog home page", "One page layout", "Light theme layout", "Attractive UI", "Minimalistic readable design", "Enhanced user experience", "Navigation bar"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726661572/Mockup48_fvbq6h.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726661585/Mockup49_qzajyi.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66eac915568a4f229637f9d5",
        title: "SaaS website landing page",
        description:
          "A SaaS website offering a sleek, user-friendly interface with powerful features like real-time analytics, seamless integrations, and automated workflows to streamline operations, enhance productivity, and deliver a top-tier digital experience.",
        longDescription:
          "The SaaS website features a sleek, user-friendly interface designed for efficiency and ease of use. It offers a customizable dashboard, real-time analytics, and robust integration options to streamline operations. With responsive design and high-performance capabilities, users can access their data and tools seamlessly across all devices. Security is a top priority, with built-in encryption and authentication. The platform also supports multi-language options, automated workflows, and interactive features to enhance user engagement and operational efficiency.",
        theme: "dark",
        category: ["business", "dark_theme", "2d", "saas", "landing_page"],
        access: "Pro",
        price: 25,
        platform: ["figma"],
        feature: ["Saas website", "One page layout", "Dark mode design", "Enhanced user focus", "Increased customer satisfaction", "Modern UI design"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726662570/Mockup51_whyzyn.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726662582/Mockup50_d1g14m.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
      {
        id: "66eacd8490bdcb1f724121b6",
        title: "SaaS Landing Page",
        description:
          "A SaaS landing page offering a sleek, user-friendly interface with powerful features like real-time analytics, seamless integrations, and automated workflows to streamline operations, enhance productivity, and deliver a top-tier digital experience. ",
        longDescription:
          "The SaaS landing page features a sleek, user-friendly interface designed for efficiency and ease of use. It offers a customizable dashboard, real-time analytics, and robust integration options to streamline operations. With responsive design and high-performance capabilities, users can access their data and tools seamlessly across all devices. Security is a top priority, with built-in encryption and authentication. The platform also supports multi-language options, automated workflows, and interactive features to enhance user engagement and operational efficiency.",
        theme: "dark",
        category: ["business", "dark_theme", "2d", "saas", "landing_page"],
        access: "Free",
        price: 0,
        platform: ["figma"],
        feature: ["Saas website", "One page layout", "Dark mode design", "Purple theme", "Enhanced user focus", "Increased customer satisfaction"],
        image: ["https://res.cloudinary.com/dv86lqkcy/image/upload/v1726663788/Mockup52_plixbi.png", "https://res.cloudinary.com/dv86lqkcy/image/upload/v1726663802/Mockup53_ax8epf.png"],
        file: "",
        datePublished: new Date("2025-03-03 08:01:50.276"),
        userId: "be208b27-21b5-4f30-93b9-4967f2dc907e",
        likes: 120,
        dislikes: 5,
        likesArray: [],
      },
    ],
    skipDuplicates: true, // Optional: Skips records with duplicate unique fields
  });

  console.log("Multiple users inserted successfully");
}

main()
  .then(() => {
    console.log("✅ Seed complete!");
  })
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
